### ISSUE TITLE
ImmuDB SDK 1.4

### ISSUE THREAD

**Issue by arriqaaq** [ankane/immudb-ruby#3]
Hello @ankane 

We have upgraded immudb sdk to versions 1.4, and wanted to provide an update on the same.

**Comment by ankane** [comment]
Hey @arriqaaq, thanks for the heads up. I only see the release candidate right now. Can you share what you mean by update? Are there breaking changes?

**Comment by arriqaaq** [comment]
Hi @ankane, thanks for checking it out!

There was a delay from our side on the release. Actually these are not breaking changes, but updated methods, and functions. From what I am aware, the ruby sdk is in sync with the python sdk right? I'll just get the release notes for better clarity on what the changes are.

**Comment by ankane** [comment]
The API mostly follows the Python API. Also, just tested with immudb 1.4.0 and everything passes.

**Comment by arriqaaq** [comment]
Hi @ankane 

Sorry for the late reply as I was waiting for the 1.4 release for python sdk to be done. 1.4 just includes additional methods and functionalities, and here is the changelog

https://github.com/codenotary/immudb-py/releases/tag/v1.4.0

**Comment by ankane** [comment]
Thanks @arriqaaq, will plan to add these as users need them (may also add some proactively).
